resolver: lts-11.14
extra-deps:
- vector-sized-1.0.2.0
- indexed-list-literals-0.2.1.1
- Useful-0.0.6
- list-extras-0.4.1.4
- toolshed-0.18.0.0
- git: https://github.com/conal/concat.git
  commit: c45b1e6b352c7be09d8e92e6669b8f6aac36063d
  subdirs:
  - classes
  - examples
  - inline
  - satisfy
  - known
  - plugin
